matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.1
        - MAJOR_VERSION=4
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.0.3
        - MAJOR_VERSION=4
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.0.3
        - MAJOR_VERSION=3
    - os: osx
      language: generic
      sudo: required
      osx_image: xcode10
      env:
        - SWIFT_VERSION=4.2
        - MAJOR_VERSION=4.2
    - os: osx
      language: generic
      sudo: required
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0.3
        - MAJOR_VERSION=4
    - os: osx
      language: generic
      sudo: required
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0.3
        - MAJOR_VERSION=3
install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
- swift test -Xswiftc -swift-version -Xswiftc $MAJOR_VERSION
